apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: default
subjects:
- kind: User
  name: skillpropil
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-describe-logs
  apiGroup: rbac.authorization.k8s.io
